LibraryApp/Controllers/BooksController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using LibraryApp.Data.Services;

namespace LibraryApp.Controllers
{
    public class BooksController : Controller
    {
        private readonly IBookService _service;

        public BooksController(IBookService service)
        {
            _service = service;
        }

        // GET: Books
        public IActionResult Index()
        {
            var items = _service.GetAll();
            return View(items);
        }

        // GET: Books/Details/5
        public IActionResult Details(Guid id)
        {
            var book = _service.GetById(id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }
    }
}

LibraryApp/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Braintree;
using LibraryApp.Data.Services;
using LibraryApp.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Stripe;

namespace LibraryApp.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly IBookService _courseService;
        private readonly IBraintreeService _braintreeService;

        public CheckoutController(IBookService courseService, IBraintreeService braintreeService)
        {
            _courseService = courseService;
            this._braintreeService = braintreeService;
        }

        public IActionResult Purchase(Guid id)
        {

            var book = _courseService.GetById(id);
            if (book == null) return NotFound();

            var gateway = _braintreeService.CreateGateway();

            var clientToken = gateway.ClientToken.Generate();

            ViewBag.ClientToken = clientToken;

            ViewBag.PurchaseAmount = book.Price;
            var data = new BookPurchaseVM
            {
                Id = book.Id,
                Description = book.Description,
                Author = book.Author,
                Thumbnail = book.Thumbnail,
                Title = book.Title,
                Price = book.Price,
                Nonce = ""
            };

            return View(data);
        }


        public IActionResult Create(BookPurchaseVM model)
        {
            var gateway = _braintreeService.GetGateway();

            var book = _courseService.GetById(model.Id);

            var request = new TransactionRequest()
            {
                Amount = Convert.ToDecimal(book.Price),
                PaymentMethodNonce = model.Nonce,
                Options = new TransactionOptionsRequest()
                {
                    SubmitForSettlement = true
                }
            };

            Result<Transaction> result = gateway.Transaction.Sale(request);

            if (result.IsSuccess())
                return View("Success");
            else
                return View("Failure");
        }

        public IActionResult BraintreePlans()
        {
            var gateway = _braintreeService.GetGateway();
            var plans = gateway.Plan.All();

            return
                View(plans);
        }

        public IActionResult SubscriptionPlan(string id)
        {
            var gateway = _braintreeService.GetGateway();


            var Subscriptionrequest = new SubscriptionRequest()
            {
              PaymentMethodToken= "My-Paymen-Token-Value",
              PlanId=id
            };

            Result<Braintree.Subscription> result = gateway.Subscription.Create(Subscriptionrequest);

            if (result.IsSuccess())
                return View("Subscribed");
            else
                return View("FailSub");
        }



        //Scripe


        public IActionResult PurchaseWithScripe(Guid id)
        {

            var book = _courseService.GetById(id);
            if (book == null) return NotFound();

            var gateway = _braintreeService.CreateGateway();

            var clientToken = gateway.ClientToken.Generate();

            ViewBag.ClientToken = clientToken;

            ViewBag.PurchaseAmount = book.Price;
            var data = new BookPurchaseVM
            {
                Id = book.Id,
                Description = book.Description,
                Author = book.Author,
                Thumbnail = book.Thumbnail,
                Title = book.Title,
                Price = book.Price,
                Nonce = ""
            };

            return View(data);
        }



        public IActionResult CreateStripe(string stripeToken, Guid id)
        {
            var book = _courseService.GetById(id);

            var chargeOptions = new ChargeCreateOptions()
            {
                Amount = (long)(Convert.ToDouble(book.Price) * 100),
                Currency = "Usd",
                Source = stripeToken,

                // if you want to add meta data then, otherwise its enought

                Metadata = new Dictionary<string, string>()
                {
                    { "BookId", book.Id.ToString()},
                    {"BookTitle",book.Title },
                    {"BookAuthor",book.Author }
                }
            };

            var service = new ChargeService();

            Charge charge = service.Create(chargeOptions);

            if (charge.Status == "succeeded")
                return View("Success");
            else
                return View("Failure");
        }
    }
}

LibraryApp/Controllers/StripeDashboardController.cs
using LibraryApp.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryApp.Controllers
{
    public class StripeDashboardController : Controller
    {
        public IActionResult Index()
        {
            var response = new StripeDashboardVM();
            var balanceService = new BalanceService();
            var balanceResult = balanceService.Get();

            response.Balance = balanceResult;

            var transactionService = new BalanceTransactionService();
            var transactionResult = transactionService.List().ToList();

            response.Transactions = transactionResult;

            var customerService = new CustomerService();

            var customerResult = customerService.List().ToList();

            response.Customers = customerResult;

            var chargeService = new ChargeService();
            var chargeResult = chargeService.List().ToList();
            response.Charges = chargeResult;


            var disputeService = new DisputeService();

            var disputeResult = disputeService.List().ToList();

            response.Disputes = disputeResult;

            var refundService = new RefundService();
            var refundResult = refundService.List().ToList();
            response.Charges = chargeResult;

            var productsService = new ProductService();
            var productsResult = productsService.List().ToList();
            response.Products = productsResult;

            return View(response);
        }
    }
}

LibraryApp/Views/Books/Details.cshtml
@model LibraryApp.Data.Models.Book

@{
    ViewData["Title"] = "Details";
}


<div class="card">
    <div class="card-body">
        <h5 class="card-title">@Model.Title <small class="text-muted">(by: @Model.Author</small>)</h5>
        <p class="card-text">@Model.Description</p>
    </div>
    <img class="card-img-bottom" src="@Model.Thumbnail" alt="Card image cap">
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

LibraryApp/Views/Books/Index.cshtml
@model IEnumerable<LibraryApp.Data.Models.Book>

@{
    ViewData["Title"] = "Index";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-6 col-xs-6" style="padding-bottom: 35px;">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">@item.Title <small class="text-muted">(by: @item.Author) </small></h5><br />
                    <p class="card-text">@item.Description</p>
                    @Html.ActionLink("Show details", "Details", "Books", new { id = item.Id })
                    @Html.ActionLink("Purchase - $" + item.Price, "Purchase", "Checkout", new { id = item.Id }, new { @class = "btn btn-success pull-right" })
                    |
                    @Html.ActionLink("Purchase With Stripe - $" + item.Price, "PurchaseWithScripe", "Checkout", new { id = item.Id }, new { @class = "btn btn-success pull-right" })
                </div>
            </div>
        </div>
    }
</div>

LibraryApp/Views/Books/Subscribe.cshtml
@{
    ViewData["Title"] = "Subscribe";
}

<h1>CONGRATULATIONS - YOU WERE SUBSCRIBED TO THE PLAN!</h1>

LibraryApp/Views/Checkout/BraintreePlans.cshtml
@model List<Braintree.Plan> 
@{
    ViewData["Title"] = "BraintreePlans";
}

<div class="row">
        @foreach (var plan in Model)
        {
            <div class="col-md-6">
                <div class="card">
                   <h3 class="card-title bg-info">@plan.Name</h3>
                    <div class="card-body">
                        <div class="card-text">
                            <p>Description : @plan.Description</p>
                            <p>Plan Price : @plan.Price</p>
                            <p>Plan Period : @plan.TrialPeriod</p>
                            <p>Plan Duration : @plan.Description</p>
                        </div>
                    </div>
                </div>

                @Html.ActionLink("Subscribe To Plan","SubscriptionPlan", "Checkout", new {@id=plan.Id},new {@class="btn btn-primary" })
            </div>
        }
</div>

LibraryApp/Views/Checkout/FailSub.cshtml
@{
    ViewData["Title"] = "FailSub";
}

<h2 class="text-center text-danger">You have Fail Subscribed This Plan!</h2>

LibraryApp/Views/Checkout/Failure.cshtml
@{
    ViewData["Title"] = "Failure";
}

<h2 class="text-center text-danger">You Transection failed!</h2>

LibraryApp/Views/Checkout/Purchase.cshtml
@model LibraryApp.Data.ViewModels.BookPurchaseVM

@{
    ViewData["Title"] = "Purchase";
}

<div class="wrapper">
    <div class="checkout container">
        <form id="payment-form" method="post" asp-controller="Checkout" asp-action="Create">
            @Html.HiddenFor(n => n.Id)
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title" name="Title" asp-for="@Model.Title">@Model.Title</h5>
                    <p class="card-text">@Model.Description</p>
                    <p class="card-text"><small class="text-muted">Author: @Model.Author</small></p>
                    <p class="card-text"><small class="text-muted">Price: @Model.Price</small></p>
                </div>
                <img style="width: 90%" class="card-img-bottom" src="@Model.Thumbnail" alt="Card image cap">
            </div>
           <section>
               <div class="btn-drop-in-wrapper">
                   <div id="bt-dropin"></div>
               </div>
           </section>
            <hr />
            <button class="btn btn-success" type="submit"><span>Confirm payment - $@Model.Price</span></button>
        
            @Html.HiddenFor(s=>s.Nonce, new {@id="nonce"})
        
        
        </form>
    </div>
</div>

<script src="https://js.braintreegateway.com/web/dropin/1.25.0/js/dropin.min.js"></script>

<script>
    var client_token = "@ViewBag.ClientToken";

    var form = document.querySelector("#payment-form");


    braintree.dropin.create({
        authorization: client_token,
        container: "#bt-dropin",
        paypal: {
            flow: 'vault'
        }
    }, function (createErr, instence) {
            form.addEventListener('submit', function (event) {
                event.preventDefault();

                instence.requestPaymentMethod(function (err, payload) {
                    if (err) {
                        return;
                    }

                    document.querySelector("#nonce").value = payload.nonce;

                    form.submit();
                });
            });
    });
</script>

LibraryApp/Views/Checkout/PurchaseWithScripe.cshtml
@model LibraryApp.Data.ViewModels.BookPurchaseVM

@{
    ViewData["Title"] = "Purchase with Stripe";
}

<div class="wrapper">
    <div class="checkout container">
        <form id="payment-form" method="post" asp-controller="Checkout" asp-action="CreateStripe">
            @Html.HiddenFor(n => n.Id)
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title" name="Title" asp-for="@Model.Title">@Model.Title</h5>
                    <p class="card-text">@Model.Description</p>
                    <p class="card-text"><small class="text-muted">Author: @Model.Author</small></p>
                    <p class="card-text"><small class="text-muted">Price: @Model.Price</small></p>
                </div>
                <img style="width: 90%" class="card-img-bottom" src="@Model.Thumbnail" alt="Card image cap">
            </div>
            <section>
                <div class="btn-drop-in-wrapper">
                    <div id="bt-dropin"></div>
                </div>
            </section>
            <hr />
          
            @Html.HiddenFor(s => s.Nonce, new { @id = "nonce" })

              <script src="https://checkout.stripe.com/checkout.js"
                        class="stripe-button"
                        data-key="pk_test_51HsWZfGr75eoraYwxEjk1AObwf5lp1qcaCNozzDKirbwYFLmSHjCfVH4dGD0dBgz94B3XWe3Me3c71BnjxAv7kLX00ALIfDd1D"
                        data-name="LibraryApp Payment"
                        data-description="@Model.Author - @Model.Title"
                        data-locale="en"
                        data-label="Confirm Payment - $@ViewBag.PurchaseAmount">
                </script>
           
        </form>
    </div>
</div>

LibraryApp/Views/Checkout/Subscribed.cshtml
@{
    ViewData["Title"] = "SubscriptionPlan";
}
<h2 class="text-center text-success">You have Successfullt Subscribed This Plan!</h2>

LibraryApp/Views/Checkout/Success.cshtml
@{
    ViewData["Title"] = "Success";
}

<h2 class="text-center text-success">You Transection was Successful!</h2>

LibraryApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Books" asp-action="Index">Library App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Checkout" asp-action="BraintreePlans">Plans</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="StripeDashboard" asp-action="Index">Stripe Dashboard</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            2020 - Library App
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

LibraryApp/Views/StripeDashboard/Index.cshtml
@using LibraryApp.Data.ViewModels;
@model StripeDashboardVM

@{
    ViewData["Title"] = "Index";
}

<h1>Stripe Overview</h1>

<div class="row">
    <div class="col-md-6">
        <h4>Available Credit: $@string.Format("{0:#.00}", Convert.ToDecimal(Model.Balance.Available.Sum(s => s.Amount)) / 100) </h4>
    </div>
    <div class="col-md-6">
        <h4>Pending Credit $@string.Format("{0:#.00}", Convert.ToDecimal(Model.Balance.Pending.Sum(s => s.Amount)) / 100)</h4>
    </div>
</div>

<div class="table">
    <table class="table-responsive">
        <thead>
            <tr>
                <th>Type</th>
                <th>Status</th>
                <th>Amount</th>
                <th>Created</th>
                <th>Available On</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Transactions)
            {
                <tr>
                    <td>@item.Type</td>
                    <td>@item.Status</td>
                    <td>$@string.Format("{0:#.00}", Convert.ToDecimal(item.Amount) / 100)</td>
                    <td>@item.Created</td>
                    <td>@item.AvailableOn</td>
                </tr>
            }

        </tbody>
    </table>
</div>

<hr />
<h3>Service Customer</h3>
<div class="table">
    <table class="table-responsive">
        <thead>
            <tr>
                <th>Name</th>
                <th>phone</th>
                <th>Amount</th>
                <th>ID</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var customer in Model.Customers)
            {
                <tr>
                    <td>@customer.Name</td>
                    <td>@customer.Phone</td>
                    <td>$@string.Format("{0:#.00}", Convert.ToDecimal(customer.Balance) / 100)</td>
                    <td>@customer.Id</td>
                </tr>
            }

        </tbody>
    </table>
</div>
<hr />
<h3>Service Charges</h3>
<div class="table">
    <table class="table-responsive">
        <thead>
            <tr>
                <th>Amount</th>
                <th>Source</th>
                <th>Receipt Email</th>
                <th>Receipt No</th>
                <th>Receipt Url</th>
                <th>Created</th>
                <th>Customer Id </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var charge in Model.Charges)
            {
                <tr>
                    <td>$@string.Format("{0:#.00}", Convert.ToDecimal(charge.Amount) / 100)</td>
                    <td>@charge.Source</td>
                    <td>@charge.ReceiptEmail</td>
                    <td>@charge.ReceiptNumber</td>
                    <td>@charge.ReceiptUrl</td>
                    <td>@charge.Created</td>
                    <td>@charge.Customer</td>
                </tr>
            }

        </tbody>
    </table>
</div>


<hr />
<h3>Service Dispure</h3>
<div class="table">
    <table class="table-responsive">
        <thead>
            <tr>
                <th>Amount</th>
                <th>Status</th>
                <th>Created</th>
                <th>Currency </th>
                <th>Reason </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var charge in Model.Disputes)
            {
                <tr>
                    <td>$@string.Format("{0:#.00}", Convert.ToDecimal(charge.Amount) / 100)</td>
                    <td>@charge.Status</td>
                    <td>@charge.Created</td>
                    <td>@charge.Currency</td>
                    <td>@charge.Reason</td>
                </tr>
            }

        </tbody>
    </table>
</div>


<hr />
<h3>Service Refund</h3>
<div class="table">
    <table class="table-responsive">
        <thead>
            <tr>
                <th>Amount</th>
                <th>Status</th>
                <th>Created</th>
                <th>Currency </th>
                <th>Reason </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var charge in Model.Refunds)
            {
                <tr>
                    <td>$@string.Format("{0:#.00}", Convert.ToDecimal(charge.Amount) / 100)</td>
                    <td>@charge.Status</td>
                    <td>@charge.Created</td>
                    <td>@charge.Currency</td>
                    <td>@charge.Reason</td>
                </tr>
            }

        </tbody>
    </table>
</div>


<hr />
<h3>Service Product</h3>
<div class="table">
    <table class="table-responsive">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Created</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var charge in Model.Products)
            {
                <tr>
                    
                    <td>@charge.Name</td>
                    <td>@charge.Description</td>
                    <td>@charge.Created</td>
                </tr>
            }

        </tbody>
    </table>
</div>